---
- name: Install Java and Tomcat
  hosts: all
  become: true

  tasks:
    - name: Install Java
      apt:
        name: openjdk-8-jre-headless

    - name: Download Tomcat
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.78/bin/apache-tomcat-8.5.78.tar.gz
        dest: /usr/

    - name: Extract Tomcat
      unarchive:
        src: /usr/apache-tomcat-8.5.78.tar.gz
        dest: /usr/
        remote_src: yes