---
- name: Java and Tomcat installation
  hosts: all
  become: true

  tasks:
    - name: Java
      apt:
        name: openjdk-8-jre-headless

    - name: Tomcat
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.62/bin/apache-tomcat-9.0.62.tar.gz
        dest: /usr/

    - name: Tomcat config
      unarchive:
        src: /usr/apache-tomcat-9.0.62.tar.gz
        dest: /usr/
        remote_src: yes